spring.application.name=gateway-service

server.port=8888

# Route 1: Identity Service Route
spring.cloud.gateway.routes[0].id=identity-service-route
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/identity/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Route 2: Product Service Route
spring.cloud.gateway.routes[1].id=product-service-route
spring.cloud.gateway.routes[1].uri=http://localhost:8080
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1


# JWT Secret (Copy chính xác chu?i Secret ? Identity Service)
jwt.secret=RikkeiEducationSuperSecretKeyForJWTTokenSigning2026!
