spring.application.name=identity-service

# ==================================
# Server Configuration
# ==================================
server.port=8080

# ==================================
# PostgreSQL Database Configuration
# ==================================
spring.datasource.url=jdbc:postgresql://localhost:5432/identity_db
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver

# ==================================
# JPA / Hibernate Configuration
# ==================================
# T? ??ng c?p nh?t / t?o c?u trúc b?ng t? Entity
spring.jpa.hibernate.ddl-auto=update

# Hi?n th? SQL query trong console log khi debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect cho PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Secret key ph?i dài t?i thi?u 256-bit (ít nh?t 32 ký t?). Thay ??i chu?i này ?? b?o m?t t?t h?n.
jwt.secret=RikkeiEducationSuperSecretKeyForJWTTokenSigning2026!
# Th?i gian h?t h?n c?a Token (3600000ms = 1 gi?)
jwt.expiration=3600000